# This is a basic workflow to help you get started with Actions

name: Deploy EKS Cluster

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: "AKIAXYKJSQETEBKWXUQ3"
          AWS_SECRET_ACCESS_KEY: "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"
        run: |
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set region "us-east-1"

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan

      - name: Apply Terraform
        run: terraform apply -auto-approve
