# This is a basic workflow to help you get started with Actions

name: Deploy EKS Cluster

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Restore Terraform state from cache
        id: cache
        uses: actions/cache@v3
        with:
          path: .terraform
          key: terraform-state-${{ github.ref }}-${{ github.sha }}

      #- name: Configure AWS Credentials
      #  env:
      #    AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID"
      #    AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY"
      #  run: |
      #    aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
      #    aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
      #    aws configure set region "us-east-1"

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan

      - name: Apply Terraform
        run: terraform apply -auto-approve

      - name: Cache updated Terraform state
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: .terraform
          key: terraform-state-${{ github.ref }}-${{ github.sha }}

      - name: Retrieve kubeconfig file path
        id: kubeconfig_path
        run: echo "kubeconfig_path=${GITHUB_WORKSPACE}/kubeconfig.yaml" >> $GITHUB_ENV

      - name: Upload kubeconfig.yaml as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: kubeconfig
          path: ${{ env.kubeconfig_path }}
