name: Deploy EKS Cluster

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Restore Terraform state from cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            .terraform
            terraform.tfstate
          key: terraform-state-${{ github.ref }}

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan

      - name: Apply Terraform
        run: terraform apply -auto-approve

      - name: Cache updated Terraform state
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: |
            .terraform
            terraform.tfstate
          key: terraform-state-${{ github.ref }}

      - name: Retrieve kubeconfig file path
        id: kubeconfig_path
        run: echo "kubeconfig_path=${GITHUB_WORKSPACE}/kubeconfig.yaml" >> $GITHUB_ENV

      - name: Upload kubeconfig.yaml as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: kubeconfig
          path: ${{ env.kubeconfig_path }}

      - name: Encode kubeconfig as base64
        run: echo "KUBECONFIG_CONTENT=$(base64 -w 0 kubeconfig.yaml)" >> $GITHUB_ENV

      - name: Set up environment and save kubeconfig as secret
        run: |
          # Install necessary dependencies
          npm install @octokit/rest tweetsodium

          # Run the script
          node save-secret.mjs
        env:
          TPA_CLASSIC_TOKEN: ${{ secrets.TPA_CLASSIC_TOKEN }}
          #PAT_FOR_SECRET_MANAGEMENT: ${{ secrets.PAT_FOR_SECRET_MANAGEMENT }}
          KUBECONFIG_CONTENT: ${{ env.KUBECONFIG_CONTENT }}


