# This is a basic workflow to help you get started with Actions

name: Deploy EKS Cluster

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      #- name: Configure AWS Credentials
      #  env:
      #    AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID"
      #    AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY"
      #  run: |
      #    aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
      #    aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
      #    aws configure set region "us-east-1"

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan - destroy

      - name: Apply Terraform
        run: terraform destroy -auto-approve
